name: Interface (Web)

on:
  push:
    paths:
      - 'index.html'
      - '.github/workflows/deploy_site.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Interface
        run: touch .nojekyll

      - name: Deploy Interface
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          # CRITICAL: Exclude the firmware folder from deletion
          exclude_assets: '**.ino,**.h,**.yml,README.md,dist,build,firmware'
          keep_files: true
          commit_message: "Update: Web Interface"
